config/routes.rb
Rails.application.routes.draw do
  resources :dizimos  
  resources :membros
  root 'membros#index'
  match 'inicio' => 'membros#index', via: 'get'
  match 'estatisticas' => 'estatisticas#index', via: 'get'
  match 'configuracao' => 'configuracao#index', via: 'get'
  match 'configuracao/acesso' => 'configuracao#acesso', via: 'PATCH'
  match 'configuracao/adicionar' => 'configuracao#adicionar', via: 'post'
  match 'mais/:id' => 'membros#mais', via: 'get'
  match 'eliminar/:id' => 'configuracao#eliminar', via: 'DELETE'
  

  devise_scope :usuario do
  	get 'login', to: 'usuarios/sessions#new'
    get 'sign_up', to: 'usuarios/registrations#new'
  	delete 'logout', to: 'usuarios/sessions#destroy'
  end

  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
    passwords: 'usuarios/passwords'
  }

  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/membro.rb
class Membro < ApplicationRecord
	default_scope { where('apagado IS NULL')}

	has_many :dizimos, :dependent => :destroy

	def self.cron_delete
		delete_all
	end

end

app/controllers/membros_controller.rb
class MembrosController < ApplicationController
  before_action :set_membro, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!


  # GET /membros
  # GET /membros.json
  def index
    if params[:search]
      respond_to do |format|
        @membros = Membro.where(["nome like ?", "%#{params[:search]}%"]).paginate(:page => params[:page], :per_page => 15)
        @quantidade = Membro.count
        @membro = Membro.new
        format.html
        format.js
      end
    else
      @membros = Membro.paginate(:page => params[:page], :per_page => 15)
      @quantidade = Membro.count
      @membro = Membro.new
    end

  end

  def mais
    respond_to do |format|
      format.js
    end
  end

  # GET /membros/1
  # GET /membros/1.json
  def show
    @dizimos = Dizimo.demembro(@membro.id)
    @dizimo = Dizimo.new
    @dizimo.membro_id = @membro.id
  end

  # GET /membros/new
  def new
    @membro = Membro.new
  end

  # GET /membros/1/edit
  def edit
  end

  # POST /membros
  # POST /membros.json
  def create
    @membro = Membro.new(membro_params)

    respond_to do |format|
      if @membro.save
        format.html { redirect_to @membro, notice: 'Membro was successfully created.' }
        format.json { render :show, status: :created, location: @membro }
        format.js
      else
        format.html { render :new }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
        format.js        
      end
    end
  end

  # PATCH/PUT /membros/1
  # PATCH/PUT /membros/1.json
  def update
    @dizimos = Dizimo.demembro(@membro.id)
    @dizimo = Dizimo.new
    @dizimo.membro_id = @membro.id
    respond_to do |format|
      if @membro.update(membro_params)
        format.html { redirect_to @membro, notice: 'Membro was successfully updated.' }
        format.json { render :show, status: :ok, location: @membro }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
        format.js        
      end
    end
  end

  # DELETE /membros/1
  # DELETE /membros/1.json
  def destroy
    #@membro.apagado = "t"
    @membro.destroy
    respond_to do |format|
      format.html { redirect_to membros_url, notice: 'Membro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membro
      @membro = Membro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membro_params
      params.require(:membro).permit(:nome, :pai, :mae, :residencia, :nacionalidade, :naturalidade, :provincia, :nascimento, :sexo, :estado_civil, :peso, :altura, :data_casamento, :agregado, :localbaptismo, :data_batismo, :localconfirmacao, :data_confirmacao, :categoriareligiosa, :cargolideranca, :sociedade, :bi, :casado, :batizado, :confirmacao, :cedula, :cartao_residente, :passaporte, :cartao_eleitoral)
    end
end

app/helpers/membros_helper.rb
module MembrosHelper
    def self.verificar(valor, comparar)
        if valor == comparar 
           "selected"
        end
    end
end

app/views/membros/_form.html.erb
<%= form_with(model: membro, local: true) do |form| %>
  <% if membro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membro.errors.count, "error") %> prohibited this membro from being saved:</h2>

      <ul>
      <% membro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :membro_nome %>
  </div>

  <div class="field">
    <%= form.label :pai %>
    <%= form.text_field :pai, id: :membro_pai %>
  </div>

  <div class="field">
    <%= form.label :mae %>
    <%= form.text_field :mae, id: :membro_mae %>
  </div>

  <div class="field">
    <%= form.label :residencia %>
    <%= form.text_field :residencia, id: :membro_residencia %>
  </div>

  <div class="field">
    <%= form.label :nacionalidade %>
    <%= form.text_field :nacionalidade, id: :membro_nacionalidade %>
  </div>

  <div class="field">
    <%= form.label :naturalidade %>
    <%= form.text_field :naturalidade, id: :membro_naturalidade %>
  </div>

  <div class="field">
    <%= form.label :provincia %>
    <%= form.text_field :provincia, id: :membro_provincia %>
  </div>

  <div class="field">
    <%= form.label :nascimento %>
    <%= form.date_select :nascimento, id: :membro_nascimento %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.check_box :sexo, id: :membro_sexo %>
  </div>

  <div class="field">
    <%= form.label :estado_civil %>
    <%= form.text_field :estado_civil, id: :membro_estado_civil %>
  </div>

  <div class="field">
    <%= form.label :peso %>
    <%= form.text_field :peso, id: :membro_peso %>
  </div>

  <div class="field">
    <%= form.label :altura %>
    <%= form.text_field :altura, id: :membro_altura %>
  </div>

  <div class="field">
    <%= form.label :data_casamento %>
    <%= form.date_select :data_casamento, id: :membro_data_casamento %>
  </div>

  <div class="field">
    <%= form.label :agregado %>
    <%= form.text_area :agregado, id: :membro_agregado %>
  </div>

  <div class="field">
    <%= form.label :localbaptismo %>
    <%= form.text_field :localbaptismo, id: :membro_localbaptismo %>
  </div>

  <div class="field">
    <%= form.label :data_batismo %>
    <%= form.date_select :data_batismo, id: :membro_data_batismo %>
  </div>

  <div class="field">
    <%= form.label :localconfirmacao %>
    <%= form.text_field :localconfirmacao, id: :membro_localconfirmacao %>
  </div>

  <div class="field">
    <%= form.label :data_confirmacao %>
    <%= form.date_select :data_confirmacao, id: :membro_data_confirmacao %>
  </div>

  <div class="field">
    <%= form.label :categoriareligiosa %>
    <%= form.text_field :categoriareligiosa, id: :membro_categoriareligiosa %>
  </div>

  <div class="field">
    <%= form.label :cargolideranca %>
    <%= form.text_field :cargolideranca, id: :membro_cargolideranca %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/membros/_membro.html.erb
  <tr class="<%= membro.id %>">
    <td><%= membro.nome.split(" ")[0] %></td>
    <td><%= membro.provincia %></td>
    <td><%= membro.nascimento.mday %>/<%= membro.nascimento.mon %>/<%= membro.nascimento.year %></td>
    <td>
      <% if membro.sexo %> Homem
      <% else %> Mulher
      <% end %></td>
    <td><%= membro.estado_civil %></td>
    <td><%= membro.categoriareligiosa %></td>
    <td><%= membro.cargolideranca %></td>
    <td class="text-center">
      <%= link_to 'Ver', membro, class: "btn btn-primary" %>
      <% if current_usuario.nivel != "tesoureiro" %>
      <button class="btn btn-warning" data-toggle="modal" data-target="#novo<%= membro.id %>">Editar</button>
      <%= link_to 'Eliminar', membro, method: :delete, class: "btn btn-danger" %>
        <% end %>
    </td>
  </tr>

app/views/membros/_mostrar.html.erb
<div class="dados">

<p class="text-center" style="font-size: 24px; margin-top: 10px;">
    <%= @membro.nome %>
</p>

  <% if current_usuario.nivel != "tesoureiro" %>
      <p class="text-center" style="font-size: 18px; margin-top: 10px;">
    <button class="btn btn-warning" data-toggle="modal" data-target="#novo<%= @membro.id %>">Editar</button>
  <%= link_to 'Eliminar', @membro, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn btn-danger" %>
</p>
  <% end %>


<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
        Dados Pessoais</a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse in">
          <ul class="list-group">
          <li class="list-group-item"><strong>Pai:</strong><%= @membro.pai %></li>
          <li class="list-group-item"><strong>Mãe:</strong> <%= @membro.mae %></li>
          <li class="list-group-item"><strong>BI:</strong> <% if @membro.bi? %> <%= @membro.bi %> <%else%> Não Informado!<%end%></li>

          <li class="list-group-item"><strong>Cédula:</strong> <% if @membro.cedula? %> <%= @membro.cedula %> <%else%> Não Informado!<%end%> </li>
          <li class="list-group-item"><strong>Passaporte:</strong> <% if @membro.passaporte? %> <%= @membro.passaporte %> <%else%> Não Informado!<%end%></li>
          <li class="list-group-item"><strong>Cartão de Eleitor:</strong> <% if @membro.cartao_eleitoral? %> <%= @membro.cartao_eleitoral %> <%else%> Não Informado!<%end%></li>
          <li class="list-group-item"><strong>Cartão de Residente:</strong> <% if @membro.cartao_residente? %> <%= @membro.cartao_residente %> <%else%> Não Informado!<%end%></li>
          
          


          <li class="list-group-item"> <strong>Residencia:</strong>      <%= @membro.residencia %></li>
          <li class="list-group-item"> <strong>Nacionalidade:</strong>      <%= @membro.nacionalidade %></li>
          <li class="list-group-item"><strong>Naturalidade:</strong>     <%= @membro.naturalidade %></li>
          <li class="list-group-item"><strong>Província:</strong>       <%= @membro.provincia %></li>
          <li class="list-group-item"><strong>Nascimento:</strong>       <%=  @membro.nascimento.mday %>/<%=  @membro.nascimento.mon %>/<%= @membro.nascimento.year %></li>
          <li class="list-group-item"> <strong>Gênero:</strong> <% if @membro.sexo %> Homem <% else %> Mulher<% end %></li>
          <li class="list-group-item"><strong>Estado Civil:</strong>         <%= @membro.estado_civil %></li>
          <li class="list-group-item"><strong>Peso:</strong>    <%= @membro.peso %></li>
          <li class="list-group-item"><strong>Altura:</strong>     <%= @membro.altura %></li>
            <% if @membro.casado? %>
              <li class="list-group-item"><strong>Data do Casamento:</strong><%= @membro.data_casamento.mday %>/<%= @membro.data_casamento.mon %>/<%= @membro.data_casamento.year %></li>
            <% end %>
          <li class="list-group-item"> <strong>Agregado Familiar:</strong>      <%= @membro.agregado %></li>
      </ul> 

    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
        Dados Relacionados à Igreja</a>
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse">
          <ul class="list-group">
          <% if @membro.batizado?%>
            <li class="list-group-item"><strong>Local do Baptismo:</strong>      <% if @membro.localbaptismo? %> <%= @membro.localbaptismo %> <% else %> Local de Baptismo não cadastrado!<% end %></li>
            <li class="list-group-item"><strong>Data de Batismo:</strong>    <%= @membro.data_batismo.mday %>/<%= @membro.data_batismo.mon %>/<%= @membro.data_batismo.year %></li>
          <% else %>
            <li class="list-group-item"><strong>Batismo:</strong>Membro não baptizado</li>
          <% end %>

          <% if @membro.confirmacao? %>
            <li class="list-group-item"><strong>Local de Confirmação:</strong>  <% if @membro.localconfirmacao? %> <%= @membro.localconfirmacao %> <% else %> Local de Confirmação não cadastrado!<% end %></li>
            <li class="list-group-item"><strong>Data Confirmação:</strong>      <%=  @membro.data_confirmacao.mday %>/<%=  @membro.data_confirmacao.mon %>/<%=  @membro.data_confirmacao.year %></li>
          <% else %>
            <li class="list-group-item"><strong>Confirmação:</strong>Informações de confirmação não cadatradas!</li>
          <% end %>


              <li class="list-group-item"><strong>Categoria Religiosa:</strong>      <%= @membro.categoriareligiosa %></li>
              <li class="list-group-item"><strong>Cargo de Liderança:</strong>   <%= @membro.cargolideranca %></li>
            <li class="list-group-item"><strong>Sociedade:</strong>   <%= @membro.sociedade %></li>
          </ul> 
    </div>
  </div>
  <% if current_usuario.nivel != "secretario"  %>
    <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
        Dízimos e Outras Contribuições</a>
      </h4>
    </div>
    <div id="collapse3" class="panel-collapse collapse">
        <div class="dizimos">
          <%= render @dizimos %>
        </div>
        <button class="btn" data-toggle="modal" data-target="#mais">Adicionar Ano</button>        
    </div>
  </div>
  <% end %>
</div>

<!-- Modal -->
<div id="mais" class="modal fade esconder" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Adicionar Ano de Registro de Dízimos</h4>
      </div>
      <%= render 'dizimos/formmm', dizimo: @dizimo %>
    </div>

  </div>
</div>


<%= render 'membros/formm', membro: @membro %>
</div>

app/views/membros/_vazio.html.erb
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td>Nenhum membro corresponde a pesquisa!</td>
    <td></td>
    <td></td>
    <td></td>
</tr>

app/views/membros/create.js.erb
$(".modal").modal("hide");

app/views/membros/edit.html.erb
<h1>Editing Membro</h1>

<%= render 'form', membro: @membro %>

<%= link_to 'Show', @membro %> |
<%= link_to 'Back', membros_path %>

app/views/membros/index.html.erb
<div class="jumbotron text-center ">
  <h1>Controle de Membros</h1>
  <p>Igreja Evangélica Congregacional em Angola - I.E.C.A</p>
  <p>Congregação de Caná</p>
</div>

<div class="main container">

  <% if current_usuario.nivel != "tesoureiro" %>
  <div class="row text-center"> 
  <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#novo">Adicionar Membro</button>   
  </div>
    <% end %>
  <p>Procure membros pelo nome, cargo, província, etc</p>
  <%= form_tag membros_path, :method => 'get', remote: true, :class => "form-inline" do %>
    <div class="form-group col-sm-10" style="padding: 0px;">
         <%= text_field_tag :search, params[:search], :class => "form-control proc col-sm-12", :type => "text", :placeholder => "Pesquisar..."%>

    </div>
    <div class="form-group col-sm-2" style="padding: 0px; padding-left: 15px;">

        <%= submit_tag "Pesquisar", :class => "btn btn-primary col-sm-12" %>

    </div>
  <% end%>
  <br>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Província</th>
          <th>Nascimento</th>
          <th>Gênero</th>
          <th>Estado Civil</th>
          <th>Ct. Religiosa</th>
          <th>Cargo</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="corpo">
        <% @membros.each do |membros| %>
          <%= render membros %>
          <%= render 'membros/formm', membro: membros %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="text-center"> 
      <%= will_paginate @membros, renderer: BootstrapPagination::Rails, previous_label: "Anteriores", next_label: "Próximos", inner_window: 1, outer_window: 0%>  
  </div>
</div>

<%= render 'membros/formm', membro: @membro %>

app/views/membros/index.js.erb
$('.corpo').empty();

<% @membros.each do |membros| %>
    $('.corpo').append('<%= j render membros %>');
    $('.corpo').append('<%= j render 'membros/formm', membro: membros %>');
<% end %>

<% if @membros.empty? %>
  $('.corpo').append('<%= j render 'membros/vazio'%>');
<% end %>

app/views/membros/mais.js.erb
alert();

app/views/membros/new.html.erb
<h1>New Membro</h1>

<%= render 'form', membro: @membro %>

<%= link_to 'Back', membros_path %>

app/views/membros/show.html.erb
<div class="membro">
  <%= render 'membros/mostrar' %>  
</div>

app/views/membros/update.js.erb
$(".esconder").modal("hide")

<% if action_name == "update" %>
    $(".dados").hide('slow', function() {
        $(".dados").remove();
        $(".membro").append('<%= j render 'membros/mostrar' %> ');    
    });
<% end %>	