config/routes.rb
Rails.application.routes.draw do
  resources :dizimos  
  resources :membros
  root 'membros#index'
  match 'inicio' => 'membros#index', via: 'get'
  match 'estatisticas' => 'estatisticas#index', via: 'get'
  match 'configuracao' => 'configuracao#index', via: 'get'
  match 'configuracao/acesso' => 'configuracao#acesso', via: 'PATCH'
  match 'configuracao/adicionar' => 'configuracao#adicionar', via: 'post'
  match 'mais/:id' => 'membros#mais', via: 'get'
  match 'eliminar/:id' => 'configuracao#eliminar', via: 'DELETE'
  

  devise_scope :usuario do
  	get 'login', to: 'usuarios/sessions#new'
    get 'sign_up', to: 'usuarios/registrations#new'
  	delete 'logout', to: 'usuarios/sessions#destroy'
  end

  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
    passwords: 'usuarios/passwords'
  }

  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dizimo.rb
class Dizimo < ApplicationRecord
  belongs_to :membro

  def self.demembro(membro_id)
  	where('membro_id = ?', membro_id)
  end

end

app/controllers/dizimos_controller.rb
class DizimosController < ApplicationController
  before_action :set_dizimo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /dizimos
  # GET /dizimos.json
  def index
    @dizimos = Dizimo.all
  end

  # GET /dizimos/1
  # GET /dizimos/1.json
  def show
  end

  # GET /dizimos/new
  def new
    @dizimo = Dizimo.new
  end

  # GET /dizimos/1/edit
  def edit
  end

  # POST /dizimos
  # POST /dizimos.json
  def create
    @dizimo = Dizimo.new(dizimo_params)

    respond_to do |format|
      if @dizimo.save
        format.html { redirect_to @dizimo, notice: 'Dizimo was successfully created.' }
        format.json { render :show, status: :created, location: @dizimo }
        format.js 
      else
        format.html { render :new }
        format.json { render json: @dizimo.errors, status: :unprocessable_entity }
        format.js 
      end
    end
  end

  # PATCH/PUT /dizimos/1
  # PATCH/PUT /dizimos/1.json
  def update
    respond_to do |format|
      if @dizimo.update(dizimo_params)
        format.html { redirect_to @dizimo, notice: 'Dizimo was successfully updated.' }
        format.json { render :show, status: :ok, location: @dizimo }
        format.js 
      else
        format.html { render :edit }
        format.json { render json: @dizimo.errors, status: :unprocessable_entity }
        format.js 
      end
    end
  end

  # DELETE /dizimos/1
  # DELETE /dizimos/1.json
  def destroy
    @dizimo.destroy
    respond_to do |format|
      format.html { redirect_to dizimos_url, notice: 'Dizimo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dizimo
      @dizimo = Dizimo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dizimo_params
      params.require(:dizimo).permit(:ano, :jan, :fev, :mar, :abr, :mai, :jun, :jul, :ago, :set, :out, :nov, :des, :membro_id, :janv, :fevv, :marv, :abrv, :maiv, :junv, :julv, :agov, :setv, :outv, :novv, :desv)
    end
end

app/helpers/dizimos_helper.rb
module DizimosHelper
end

app/views/dizimos/_dizimo.html.erb
<button class="btn" data-toggle="modal" data-target="#modal_<%= dizimo.ano %>"><%= dizimo.ano %></button> 


  <!-- Modal -->
<div class="modal fade esconder" id="modal_<%= dizimo.ano %>" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4><span class="glyphicon glyphicon-lock"></span> Dizimos de <%= dizimo.ano %> </h4>
      </div>
      <%= render 'dizimos/formm', dizimo: dizimo %>
    </div>
  </div>
</div>

app/views/dizimos/_form.html.erb
<%= form_with(model: dizimo, local: true) do |form| %>
  <% if dizimo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dizimo.errors.count, "error") %> prohibited this dizimo from being saved:</h2>

      <ul>
      <% dizimo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ano %>
    <%= form.text_field :ano, id: :dizimo_ano %>
  </div>

  <div class="field">
    <%= form.label :jan %>
    <%= form.check_box :jan, id: :dizimo_jan %>
  </div>

  <div class="field">
    <%= form.label :fev %>
    <%= form.check_box :fev, id: :dizimo_fev %>
  </div>

  <div class="field">
    <%= form.label :mar %>
    <%= form.check_box :mar, id: :dizimo_mar %>
  </div>

  <div class="field">
    <%= form.label :abr %>
    <%= form.check_box :abr, id: :dizimo_abr %>
  </div>

  <div class="field">
    <%= form.label :mai %>
    <%= form.check_box :mai, id: :dizimo_mai %>
  </div>

  <div class="field">
    <%= form.label :jun %>
    <%= form.check_box :jun, id: :dizimo_jun %>
  </div>

  <div class="field">
    <%= form.label :jul %>
    <%= form.check_box :jul, id: :dizimo_jul %>
  </div>

  <div class="field">
    <%= form.label :ago %>
    <%= form.check_box :ago, id: :dizimo_ago %>
  </div>

  <div class="field">
    <%= form.label :set %>
    <%= form.check_box :set, id: :dizimo_set %>
  </div>

  <div class="field">
    <%= form.label :out %>
    <%= form.check_box :out, id: :dizimo_out %>
  </div>

  <div class="field">
    <%= form.label :nov %>
    <%= form.check_box :nov, id: :dizimo_nov %>
  </div>

  <div class="field">
    <%= form.label :des %>
    <%= form.check_box :des, id: :dizimo_des %>
  </div>

  <div class="field">
    <%= form.label :membro_id %>
    <%= form.text_field :membro_id, id: :dizimo_membro_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dizimos/_formm.html.erb
<%= form_with(model: dizimo, remote: true, id: dizimo.id) do |form| %>
 
  <div class="modal-body">
        <div class="field hidden">
          <%= form.label :ano %>
          <%= form.text_field :ano, id: :dizimo_ano %>
        </div>

        <div class="field checkbox">
          <%= form.label :jan, "Janeiro" %>
          <input name="dizimo[jan]" type="hidden" value="0">
          <input id="dizimo_jan" data-toggle="collapse" data-target="#jan<%= dizimo.id %>" type="checkbox" value="1" <% if dizimo.jan? %> checked="checked" <% end %> name="dizimo[jan]" class="collapsed">

          <div id="jan<%= dizimo.id %>" class="collapse
            <% if dizimo.jan? %> in
            <% end %>">
            <%= form.text_field :janv, id: :dizimo_janvv, class: "form-control", :placeholder => "Valor..." %>
          </div>


        </div>

        <div class="field checkbox">
          <%= form.label :fev, "Fevereiro" %>
          <input name="dizimo[fev]" type="hidden" value="0">
          <input id="dizimo_fev" data-toggle="collapse" data-target="#fev<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.fev? %> checked="checked"
                 <% end %> name="dizimo[fev]" class="collapsed">

          <div id="fev<%= dizimo.id %>" class="collapse
                      <% if dizimo.fev? %> in
                      <% end %>">
            <%= form.text_field :fevv, id: :dizimo_fevv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :mar, "Março" %>
          <input name="dizimo[mar]" type="hidden" value="0">
          <input id="dizimo_mar" data-toggle="collapse" data-target="#mar<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.mar? %> checked="checked"
                 <% end %> name="dizimo[mar]" class="collapsed">

          <div id="mar<%= dizimo.id %>" class="collapse
                                <% if dizimo.mar? %> in
                                <% end %>">
            <%= form.text_field :marv, id: :dizimo_marv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :abr, "Abril" %>
          <input name="dizimo[abr]" type="hidden" value="0">
          <input id="dizimo_abr" data-toggle="collapse" data-target="#abr<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.abr? %> checked="checked"
                 <% end %> name="dizimo[abr]" class="collapsed">

          <div id="abr<%= dizimo.id %>" class="collapse
                                          <% if dizimo.abr? %> in
                                          <% end %>">
            <%= form.text_field :abrv, id: :dizimo_abrv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :mai, "Maio" %>
          <input name="dizimo[mai]" type="hidden" value="0">
          <input id="dizimo_mai" data-toggle="collapse" data-target="#mai<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.mai? %> checked="checked"
                 <% end %> name="dizimo[mai]" class="collapsed">

          <div id="mai<%= dizimo.id %>" class="collapse
                                                    <% if dizimo.mai? %> in
                                                    <% end %>">
            <%= form.text_field :maiv, id: :dizimo_maiv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :jun, "Junho" %>
          <input name="dizimo[jun]" type="hidden" value="0">
          <input id="dizimo_jun" data-toggle="collapse" data-target="#jun<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.jun? %> checked="checked"
                 <% end %> name="dizimo[jun]" class="collapsed">

          <div id="jun<%= dizimo.id %>" class="collapse
                                                              <% if dizimo.jun? %> in
                                                              <% end %>">
            <%= form.text_field :junv, id: :dizimo_junv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :jul, "Julho" %>
          <input name="dizimo[jul]" type="hidden" value="0">
          <input id="dizimo_jul" data-toggle="collapse" data-target="#jul<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.jul? %> checked="checked"
                 <% end %> name="dizimo[jul]" class="collapsed">

          <div id="jul<%= dizimo.id %>" class="collapse
                                                                        <% if dizimo.jul? %> in
                                                                        <% end %>">
            <%= form.text_field :julv, id: :dizimo_julv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :ago, "Agosto" %>
          <input name="dizimo[ago]" type="hidden" value="0">
          <input id="dizimo_ago" data-toggle="collapse" data-target="#ago<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.ago? %> checked="checked"
                 <% end %> name="dizimo[ago]" class="collapsed">

          <div id="ago<%= dizimo.id %>" class="collapse
                                                                                  <% if dizimo.ago? %> in
                                                                                  <% end %>">
            <%= form.text_field :agov, id: :dizimo_agov, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :set, "Setembro" %>
          <input name="dizimo[set]" type="hidden" value="0">
          <input id="dizimo_set" data-toggle="collapse" data-target="#set<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.set? %> checked="checked"
                 <% end %> name="dizimo[set]" class="collapsed">

          <div id="set<%= dizimo.id %>" class="collapse
                                                                                            <% if dizimo.set? %> in
                                                                                            <% end %>">
            <%= form.text_field :setv, id: :dizimo_setv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :out, "Outubro" %>
          <input name="dizimo[out]" type="hidden" value="0">
          <input id="dizimo_out" data-toggle="collapse" data-target="#out<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.out? %> checked="checked"
                 <% end %> name="dizimo[out]" class="collapsed">

          <div id="out<%= dizimo.id %>" class="collapse
                                                                                                      <% if dizimo.out? %> in
                                                                                                      <% end %>">
            <%= form.text_field :outv, id: :dizimo_outv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :nov, "Novembro" %>
          <input name="dizimo[nov]" type="hidden" value="0">
          <input id="dizimo_nov" data-toggle="collapse" data-target="#nov<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.nov? %> checked="checked"
                 <% end %> name="dizimo[nov]" class="collapsed">

          <div id="nov<%= dizimo.id %>" class="collapse
                                                                                                                <% if dizimo.nov? %> in
                                                                                                                <% end %>">
            <%= form.text_field :novv, id: :dizimo_novv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field checkbox">
          <%= form.label :des, "Dezembro" %>
          <input name="dizimo[des]" type="hidden" value="0">
          <input id="dizimo_des" data-toggle="collapse" data-target="#des<%= dizimo.id %>" type="checkbox" value="1"
                 <% if dizimo.des? %> checked="checked"
                 <% end %> name="dizimo[des]" class="collapsed">

          <div id="des<%= dizimo.id %>" class="collapse
                                                                                                                          <% if dizimo.des? %> in
                                                                                                                          <% end %>">
            <%= form.text_field :desv, id: :dizimo_desv, class: "form-control", :placeholder => "Valor..." %>
          </div>
        </div>

        <div class="field hidden">
          <%= form.label :membro_id %>
          <%= form.text_field :membro_id, id: :dizimo_membro_id %>
        </div>
  </div>
      
  <div class="modal-footer">
      <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal">
          <span class="glyphicon glyphicon-remove"></span> Cancelar
      </button>
      <button type="submit" name="commit" class="btn btn-primary btn-default pull-left">
          <span class="glyphicon glyphicon-remove"></span> Salvar
      </button>     
  </div>


  
<% end %>

app/views/dizimos/_formmm.erb
<%= form_with(model: dizimo, remote: true) do |form| %>
 
  <div class="modal-body">
        <div class="field">
          <%= form.label :ano %>
          <%= form.text_field :ano, id: :dizimo_ano %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :jan %>
          <%= form.check_box :jan, id: :dizimo_jan %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :fev %>
          <%= form.check_box :fev, id: :dizimo_fev %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :mar %>
          <%= form.check_box :mar, id: :dizimo_mar %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :abr %>
          <%= form.check_box :abr, id: :dizimo_abr %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :mai %>
          <%= form.check_box :mai, id: :dizimo_mai %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :jun %>
          <%= form.check_box :jun, id: :dizimo_jun %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :jul %>
          <%= form.check_box :jul, id: :dizimo_jul %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :ago %>
          <%= form.check_box :ago, id: :dizimo_ago %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :set %>
          <%= form.check_box :set, id: :dizimo_set %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :out %>
          <%= form.check_box :out, id: :dizimo_out %>
        </div>

        <div class="field hidden checkbox">
          <%= form.label :nov %>
          <%= form.check_box :nov, id: :dizimo_nov %>
        </div>

        <div class="field hidden">
          <%= form.label :des %>
          <%= form.check_box :des, id: :dizimo_des %>
        </div>

        <div class="field hidden">
          <%= form.label :membro_id %>
          <%= form.text_field :membro_id, id: :dizimo_membro_id %>
        </div>
  </div>
      
  <div class="modal-footer">
      <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal">
          <span class="glyphicon glyphicon-remove"></span> Cancelar
      </button>
      <button type="submit" name="commit" class="btn btn-primary btn-default pull-left">
          <span class="glyphicon glyphicon-remove"></span> Salvar
      </button>   
  </div>  
<% end %>

app/views/dizimos/create.js.erb
$(".esconder").modal("hide")
$('.dizimos').append('<%= j render @dizimo %>');

app/views/dizimos/edit.html.erb
<h1>Editing Dizimo</h1>

<%= render 'form', dizimo: @dizimo %>

<%= link_to 'Show', @dizimo %> |
<%= link_to 'Back', dizimos_path %>

app/views/dizimos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dizimos</h1>

<table>
  <thead>
    <tr>
      <th>Ano</th>
      <th>Jan</th>
      <th>Fev</th>
      <th>Mar</th>
      <th>Abr</th>
      <th>Mai</th>
      <th>Jun</th>
      <th>Jul</th>
      <th>Ago</th>
      <th>Set</th>
      <th>Out</th>
      <th>Nov</th>
      <th>Des</th>
      <th>Membro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dizimos.each do |dizimo| %>
      <tr>
        <td><%= dizimo.ano %></td>
        <td><%= dizimo.jan %></td>
        <td><%= dizimo.fev %></td>
        <td><%= dizimo.mar %></td>
        <td><%= dizimo.abr %></td>
        <td><%= dizimo.mai %></td>
        <td><%= dizimo.jun %></td>
        <td><%= dizimo.jul %></td>
        <td><%= dizimo.ago %></td>
        <td><%= dizimo.set %></td>
        <td><%= dizimo.out %></td>
        <td><%= dizimo.nov %></td>
        <td><%= dizimo.des %></td>
        <td><%= dizimo.membro %></td>
        <td><%= link_to 'Show', dizimo %></td>
        <td><%= link_to 'Edit', edit_dizimo_path(dizimo) %></td>
        <td><%= link_to 'Destroy', dizimo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dizimo', new_dizimo_path %>

app/views/dizimos/new.html.erb
<h1>New Dizimo</h1>

<%= render 'form', dizimo: @dizimo %>

<%= link_to 'Back', dizimos_path %>

app/views/dizimos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ano:</strong>
  <%= @dizimo.ano %>
</p>

<p>
  <strong>Jan:</strong>
  <%= @dizimo.jan %>
</p>

<p>
  <strong>Fev:</strong>
  <%= @dizimo.fev %>
</p>

<p>
  <strong>Mar:</strong>
  <%= @dizimo.mar %>
</p>

<p>
  <strong>Abr:</strong>
  <%= @dizimo.abr %>
</p>

<p>
  <strong>Mai:</strong>
  <%= @dizimo.mai %>
</p>

<p>
  <strong>Jun:</strong>
  <%= @dizimo.jun %>
</p>

<p>
  <strong>Jul:</strong>
  <%= @dizimo.jul %>
</p>

<p>
  <strong>Ago:</strong>
  <%= @dizimo.ago %>
</p>

<p>
  <strong>Set:</strong>
  <%= @dizimo.set %>
</p>

<p>
  <strong>Out:</strong>
  <%= @dizimo.out %>
</p>

<p>
  <strong>Nov:</strong>
  <%= @dizimo.nov %>
</p>

<p>
  <strong>Des:</strong>
  <%= @dizimo.des %>
</p>

<p>
  <strong>Membro:</strong>
  <%= @dizimo.membro %>
</p>

<%= link_to 'Edit', edit_dizimo_path(@dizimo) %> |
<%= link_to 'Back', dizimos_path %>

app/views/dizimos/update.js.erb
$(".esconder").modal("hide")