config/routes.rb
Rails.application.routes.draw do
  resources :dizimos  
  resources :membros
  root 'membros#index'
  match 'inicio' => 'membros#index', via: 'get'
  match 'estatisticas' => 'estatisticas#index', via: 'get'
  match 'configuracao' => 'configuracao#index', via: 'get'
  match 'configuracao/acesso' => 'configuracao#acesso', via: 'PATCH'
  match 'configuracao/adicionar' => 'configuracao#adicionar', via: 'post'
  match 'mais/:id' => 'membros#mais', via: 'get'
  match 'eliminar/:id' => 'configuracao#eliminar', via: 'DELETE'
  

  devise_scope :usuario do
  	get 'login', to: 'usuarios/sessions#new'
    get 'sign_up', to: 'usuarios/registrations#new'
  	delete 'logout', to: 'usuarios/sessions#destroy'
  end

  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
    passwords: 'usuarios/passwords'
  }

  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IECA - Controle Membros</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="<%= image_path("favicon.ico") %>">
    </head>

  <body>
    <nav class="navbar navbar-default navbar-md" style="margin-bottom: 0px;">
          <div class="wrap">
              <div class="container-fluid">
                  <div class="navbar-header text-center">
                    <a class="navbar-brand " style="padding-top: 5px;" href="/"> <img src="<%= image_path("logo.png") %>" style="height: 60px;"/> I.E.C.A - Membros</a>
                  </div>
                <div class="navbar-collapse collapse">
                  <ul class="nav navbar-nav navbar-right">
                    <% if usuario_signed_in? %>
                      <li><a href="/membros">Membros</a></li>
                      <li><a href="/configuracao">Configurações</a></li>
                      <li><a href="/estatisticas">Estatísticas</a></li>
                      <li><%= link_to "Sair", destroy_usuario_session_path, method: :delete %></li>
                    <% else %>
                      <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span>Entrar</a></li>
                    <% end %>
                  </ul>
                </div>
            </div>
          </div>
    </nav>

    <%= yield %>
  </body>
</html>